### ISSUE TITLE
NFS module

### ISSUE THREAD

**Issue by samip5** [Lochnair/kernel_e50#1]
How can I build a NFS module for my ER-X?

Current kernel: Linux ER-X 4.14.54-UBNT #1 SMP Mon Jul 8 05:11:07 UTC 2019 mips GNU/Linux

**Comment by Lochnair** [comment]
If you want to build it yourself, start by looking at what the [Jenkinsfile](https://github.com/Lochnair/kernel_e50/blob/v2.0.6/master/Jenkinsfile) does.

However, I'm also happy to enable modules in this repository if you'd like. I went ahead did that in the new [v2.0.6/nfs](https://github.com/Lochnair/kernel_e50/tree/v2.0.6/nfs) branch, see resulting modules [here](https://build.lochnair.net/job/ubiquiti/job/kernel_e50/job/v2.0.6%252Fnfs/).

For future reference, this is how to modify the default config for inclusion in this repo.

Generate a .config file from the existing defconfig.
```bash
make ARCH=mips ubnt_er_e50_defconfig
```

Do whatever changes you want here.
```bash
make ARCH=mips menuconfig
```

Change it back to defconfig "format" and replace the old one.
```bash
make ARCH=mips savedefconfig
mv defconfig arch/mips/configs/ubnt_er_e50_defconfig
```
Now add the changes to Git and create a PR from it.

**Comment by samip5** [comment]
Somehow I managed to soft brick the ER-X when I bult the kernel module myself and installed it, and tried to mount a share with it. The whole device just froze and wouldn't start up with routing services anymore.

**Comment by misyntropy** [comment]
FWIW, I ran modprobe with a self-built module on the running OS rather than installing it, it froze instantly and rebooted.
